version: '3.1'

services:
  app:
    build: .
    container_name: my-nuxt-app
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
    command: sh -c "node .output/server/index.mjs"
  mongodb:
    image: mongo:4.4
    container_name: my-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    command: [--auth]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=userAdmin
      - MONGO_INITDB_ROOT_PASSWORD=userAdmin
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
volumes:
  mongodb_data: